[package]
name = "rosti"
version = "0.1.0"
authors = ["Marcel Goethals <marcel@wolkenmachine.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
image = "0.23.14"